name: psico_help
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Rotas e injecao de dependencia 
  flutter_modular: ^1.2.5+1
  # Firebase
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.6
  firebase_database:
  firebase_auth: ^0.16.1
  # Google signing
  google_sign_in: ^4.5.1
  # Gerencia de estado
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  flutter_rating_bar: ^3.0.1+1
  shared_preferences: ^0.5.7+3
  font_awesome_flutter: ^8.8.1 
  flare_flutter: ^2.0.3
  splashscreen: ^1.2.0
 



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.0.3
  build_runner:

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoRegular.ttf
        - asset: assets/fonts/NunitoSemiBold.ttf

  # - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  
